version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: homely-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    expose:
      - "8000"
